Repository ReDI-School/F24-Berlin-Web-Circle, pull requests merged in 2024-10, with the labels that each got.

#102 Feature add product highlights
  src/components/ProductHighlight/ProductHighlight.jsx
  src/components/ProductHighlight/ProductHighlight.module.css
  src/constants/constants.js
  src/icons/CalendarIcon.jsx
  src/icons/DoorIcon.jsx
  src/icons/MedalIcon.jsx
  src/icons/PinIcon.jsx
  src/icons/index.js
  src/pages/ProductPage.jsx
Labels: Freaky components, feature

#106 Bug/fix root import path
  src/components/ProductCard/ProductCard.jsx
  src/main.jsx
Labels: Freaky components

#137 Convert folder names to PascalCase
  src/App.jsx
  src/components/FavoriteStay/FavoriteStay.jsx
  src/components/MapView/MapView.jsx
  src/components/MapView/MapView.module.css
  src/components/PersonProfile/PersonProfile.jsx
  src/components/PersonProfile/PersonProfile.module.css
  src/components/ProductDescription/ProductDescription.jsx
  src/components/ProductDescription/ProductDescription.module.css
  src/components/ProductDescription/ProductDescriptionPopup.jsx
  src/components/ProductDescription/ProductDescriptionPopup.module.css
  src/components/ProductGallery/ProductGallery.jsx
  src/components/ProductGallery/ProductGallery.module.css
  src/components/ProductSummary/ProductSummary.jsx
  src/components/ProductSummary/ProductSummary.module.css
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/pages/ProductPage.jsx
Labels: Freaky components

#135 Adding map to mapView component
  .gitignore
  package-lock.json
  package.json
  src/components/MapDisplay/MapDisplay.jsx
  src/components/MapDisplay/MapDisplay.module.css
  src/components/MapView/MapView.jsx
  src/icons/AirbnbIcon.jsx
  src/icons/ArrowRightIcon.jsx
  src/icons/HomeIcon.jsx
Labels: Freaky components

#142 Feature/amenities-
  src/components/Amenities/Amenities.jsx
  src/components/Amenities/Amenities.module.css
  src/icons/BackyardIcon.jsx
  src/icons/BalconyIcon.jsx
  src/icons/FirepitIcon.jsx
  src/icons/FireplaceIcon.jsx
  src/icons/KitchenIcon.jsx
  src/icons/ParkingIcon.jsx
  src/icons/PetsIcon.jsx
  src/icons/SaunaIcon.jsx
  src/icons/WifiIcon.jsx
  src/icons/WorkspaceIcon.jsx
  src/icons/index.js
  src/pages/ProductPage.jsx
Labels: Freaky components

#104 Feature/product gallery popup
  src/components/ProductGallery/ProductGallery.jsx
  src/components/ProductGalleryPopup/ProductGalleryPopup.jsx
  src/components/ProductGalleryPopup/ProductGalleryPopup.module.css
  src/icons/HeartIcon.jsx
  src/icons/LeftArrowIcon.jsx
  src/icons/ShareIcon.jsx
Labels: Freaky components

#154 sticky reservation card
  src/pages/ProductPage.module.css
Labels: Freaky components

#172 adding backend to the project
  package-lock.json
  package.json
  server/index.js
  server/package-lock.json
  server/package.json
  src/App.jsx
Labels: DataDogs

#199 Feature/endpoint get data specific place
  server/index.js
  server/src/data/places.json
  src/App.jsx
  src/components/HeaderUserMenu/HeaderUserMenu.jsx
  src/main.jsx
  src/pages/ProductPage.jsx
Labels: DataDogs

#205 Removing the dark mode
  src/index.css
Labels: DataDogs

#226 More products and images in places.json
  server/src/data/places.json
Labels: DataDogs, Sprint 2 Demo

#234 fix the title in product page to be visible
  src/pages/ProductPage.module.css
Labels: Sprint 2 Demo

#211 carusel+shareModal debuging
  src/App.jsx
Labels: bug

#201 Feature/calendar increments buttons
  src/App.jsx
  src/components/DataIncrementsButtonForTheCalendar/DataIncrementsButtonForTheCalendar.css
  src/components/DataIncrementsButtonForTheCalendar/DataIncrementsButtonForTheCalendar.jsx
Labels: feature, Pixel Ninjas
